version: '3.3'

services:
  db:
    image: postgres:11.1
    volumes:
      - "./services/app/config/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - pgdata2:/var/lib/postgresql/data
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "npm run start"
    env_file: ".env"
    ports:
     - "3000:3000"
    depends_on:
      - db
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
  web:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    volumes:
      - "./services/nginx/myConfig.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app

volumes:
  pgdata2: